const PORTFOLIO_DATA = {
  "categoryOrder": ["branding", "social-media", "3d-design", "video-editing", "menu-design", "ui-website"],

  "categories": {
    "branding": { "num": "01", "title": "Branding", "script": "Identity", "tagline": "Visual identities built to last — logos, systems, packaging, and everything in between." },
    "social-media": { "num": "02", "title": "Social Media", "script": "Creatives", "tagline": "Content that earns attention without begging for it." },
    "3d-design": { "num": "03", "title": "3D Visuals", "script": "Cinematic Reality", "tagline": "Product renders and cinematic scenes built in Blender — where lighting does the talking." },
    "video-editing": { "num": "04", "title": "Motion & Video", "script": "Edits", "tagline": "Cuts, motion graphics, and VFX work that moves — in every sense of the word." },
    "menu-design": { "num": "05", "title": "Menu Design", "script": "Menus", "tagline": "Print menus that sell the experience before the food arrives." },
    "ui-website": { "num": "06", "title": "UI & Website", "script": "Digital", "tagline": "Landing pages and websites designed to convert, not just impress." }
  },

  "projects": {

    "branding": [
      {
        "id": "layali-cafe",
        "name": "Layali Café",
        "year": "2026",
        "category": "Brand Identity",
        "industry": "Food & Beverage",
        "blurb": "Two scripts. One voice. A café identity that feels like a quiet Arabian evening.",
        "overview": "The brief was simple: a café that feels like stepping into a calm evening somewhere in the Middle East. The wordmark works in both Arabic and Latin — not as a translation, but as a single idea expressed in two alphabets. The palette runs on deep brown, muted gold, and near-black: colors that feel expensive without trying. Every application, from cup sleeve to menu, holds the same quiet confidence. No loud gestures. Just a brand that knows exactly what it is.",
        "services": ["Brand Strategy", "Logo Design", "Bilingual Typography", "Brand Applications"],
        "deliverables": ["Primary & Secondary Logo", "Arabic & Latin Wordmark", "Brand Guidelines", "Color & Typography System", "Cup Sleeve", "Menu Cover", "Social Media Kit"],
        "software": ["Illustrator", "Photoshop", " "],
        "challenge": "The identity had to operate fluently in both Arabic and Latin script without feeling like a translation exercise. Each script carries different visual weight, spacing logic, and cultural resonance — reconciling them into a single coherent brand voice was the real design problem.",
        "solution": "I developed a wordmark system where both scripts share identical proportions, optical weight, and spacing rhythm. The palette and finishing choices — deep brown, aged gold — do the cultural work so the typography doesn't have to.",
        "results": ["Established a premium bilingual brand identity", "Achieved visual parity across Arabic and Latin applications", "Produced a complete brand system from concept to print-ready files", "Delivered a scalable identity that holds across every physical touchpoint"],
        "cover": "img/work/cover layali.jpg",
        "gallery": ["img/work/layali-showcase.jpg"]
      },
      {
        "id": "jjj-holdings",
        "name": "JJJ Holdings",
        "year": "2026",
        "category": "Brand Identity",
        "industry": "Corporate",
        "blurb": "Authority communicated before anyone reads a word.",
        "overview": "Investment companies live and die by first impressions. JJJ Holdings needed an identity that read as stable, serious, and built for the long run — not a startup trying to look corporate. The mark is geometric and precise. The typography is set wide and tight. The color system is minimal: deep navy, clean white, one restrained accent. Nothing decorative. Everything deliberate. The kind of brand that earns trust without asking for it.",
        "services": ["Brand Strategy", "Logo Design", "Visual Identity System", "Corporate Communications Design"],
        "deliverables": ["Primary Logo & Variations", "Brand Guidelines", "Typography System", "Color Palette", "Business Cards", "Letterhead", "Presentation Deck Template", "Email Signature"],
        "software": ["Illustrator", "Photoshop", " "],
        "challenge": "In the investment sector, most identities converge around the same visual language: dark navy, serif type, understated marks. The client needed to occupy that space of authority while remaining genuinely distinct from the competition.",
        "solution": "I built the identity around a geometric mark that reads as engineered rather than styled — constructed with mathematical precision and set against wide-tracking type that amplifies the sense of measured confidence. Every element is deliberate; nothing is decorative.",
        "results": ["Built a board-ready corporate identity system", "Established clear visual authority across all communications", "Created a design language adaptable across print and digital", "Delivered complete stationery and presentation assets"],
        "cover": "img/work/cover jjj.jpg",
        "gallery": ["img/work/jjj-showcase.jpg"]
      },
      {
        "id": "simple-sundial",
        "name": "Simple Sundial",
        "year": "2026",
        "category": "Brand Identity",
        "industry": "Luxury Branding",
        "blurb": "A lifestyle identity where the brand lives in its negative space.",
        "overview": "Some briefs arrive fully formed. Simple Sundial was one of them: a lifestyle brand for people who buy less but buy better. The name pointed the direction — time, craft, patience. The identity leans into warm earth tones and a wordmark with just enough character to feel handmade without being sloppy. No icons, no supplementary marks, no decoration that doesn't earn its place. The brand lives in what's left out.",
        "services": ["Brand Identity", "Logo Design", "Packaging Design", "Typography"],
        "deliverables": ["Primary Wordmark", "Brand Guidelines", "Typography System", "Color Palette", "Packaging Suite", "Hang Tags", "Tissue Paper", "Brand Stationery"],
        "software": ["Illustrator", "Photoshop", " "],
        "challenge": "The client wanted a lifestyle identity that felt earned rather than designed — the kind of brand that looks like it emerged from the product rather than being applied to it. Avoiding both the cold precision of luxury minimalism and the clutter of artisanal branding was a precise balancing act.",
        "solution": "I restricted the system to a wordmark and palette only — no icon, no badge, no supplementary mark. The warmth comes from material choices and type treatment rather than decoration. The brand says 'I know what I am' without having to announce it.",
        "results": ["Developed a restraint-led brand identity with distinct market positioning", "Created a packaging system that elevates the unboxing experience", "Built a visual language that scales from hang tag to retail signage", "Established premium brand perception without premium budget waste"],
        "cover": "img/work/cover sundial.jpg",
        "gallery": ["img/work/sundial-showcase.jpg"]
      },
      {
        "id": "tasty-shop",
        "name": "Tasty Shop",
        "year": "2026",
        "category": "Brand Identity",
        "industry": "Food & Beverage",
        "blurb": "Joyful enough for kids. Refined enough that adults carry it proudly.",
        "overview": "Ice cream is one of the few products where the brand is allowed to be genuinely joyful — so that's exactly what was made. Tasty Shop runs on soft pastels, rounded letterforms, and a mark with enough personality to work on a cup, a tote, or a shopfront awning. The challenge was keeping it fun without making it childish. The result hits that line: friendly enough for kids, considered enough that adults don't feel embarrassed carrying it.",
        "services": ["Brand Identity", "Logo Design", "Packaging Design", "Retail Signage Design"],
        "deliverables": ["Primary Logo & Icon", "Brand Guidelines", "Color & Typography System", "Cup & Packaging Design", "Tote Bag", "Shopfront Awning Art", "Social Media Templates"],
        "software": ["Illustrator", "Photoshop", " "],
        "challenge": "Most ice cream brands collapse into one of two failure modes: aggressively childish or aggressively minimal. Neither fits a neighbourhood shop trying to build a loyal, multigenerational following. The design had to be warm and approachable without being cute.",
        "solution": "I developed the identity around rounded geometric forms and a soft pastel palette that nods to nostalgia without borrowing from any particular era. The mark is legible at shopfront scale and intimate enough at cup size — both ends of the range were tested before anything was finalised.",
        "results": ["Created a brand system with genuine cross-demographic appeal", "Designed packaging and signage assets ready for production", "Established a recognisable visual identity across every physical format", "Built a flexible brand architecture adaptable as the product line grows"],
        "cover": "img/work/cover tasty.jpg",
        "gallery": ["img/work/tasty-showcase.jpg"]
      },
      {
        "id": "golden-hearth",
        "name": "Golden Hearth",
        "year": "2026",
        "category": "Brand Identity",
        "industry": "Restaurant",
        "blurb": "A mark built on the simplest act of hospitality — handing someone a spoon.",
        "overview": "The spoon wasn't a random choice. It's the first thing you hold when you sit down — familiar, warm, universal. Golden Hearth's mark is built around it: a simple symbol that carries the whole idea of hospitality without needing to explain itself. The serif wordmark sits alongside it with enough weight to own a menu cover and enough elegance to work embossed on a napkin ring. Warm gold. Deep background. An identity that earns its place at the table.",
        "services": ["Brand Identity", "Logo Design", "Hospitality Brand Applications", "Print Design"],
        "deliverables": ["Primary Logo & Symbol", "Brand Guidelines", "Typography & Color System", "Menu Design", "Business Cards", "Napkin Design", "Signage Artwork", "Social Media Kit"],
        "software": ["Illustrator", "Photoshop", " "],
        "challenge": "The restaurant occupied a mid-to-premium price point where the identity had to feel inviting rather than intimidating — warm enough to encourage walk-ins, refined enough to hold up on a fine-dining table. Most hospitality brands fail at one end of that range.",
        "solution": "I centred the identity on the spoon symbol — an object that is universally understood as a gesture of welcome. The warm gold palette and serif wordmark do the heavy lifting on quality signals, while the mark itself keeps the whole system approachable.",
        "results": ["Delivered a hospitality identity with strong warmth and premium positioning", "Created a print system that works across menu, signage, and stationery", "Built brand applications ready for immediate production", "Established a visual personality consistent from shopfront to table"],
        "cover": "img/work/cover golden.jpg",
        "gallery": ["img/work/golden-showcase.jpg"]
      }
    ],

    "social-media": [
      {
        "id": "hospitality-hotels",
        "name": "Hospitality & Luxury Hotels",
        "year": "2026",
        "category": "Hospitality Marketing",
        "industry": "Luxury Hotels",
        "blurb": "Social content designed to make a hotel feel like a destination before check-in.",
        "overview": "Luxury hospitality demands visuals that inspire emotion before the booking is made. This collection showcases social media campaigns for hotels, beach resorts, and premium destinations — restrained typography, cinematic photography, and editorial layouts built to elevate brand perception rather than push promotional messages. Every post is designed to feel like a page from a travel magazine that happens to have a link in the bio.",
        "services": ["Creative Direction", "Editorial Design", "Luxury Visual Design", "Campaign Design"],
        "deliverables": ["Instagram Feed Posts", "Stories Templates", "Facebook Campaign Visuals", "Reels Cover Frames", "Seasonal Campaign Assets"],
        "software": ["Photoshop", "Illustrator"],
        "challenge": "Luxury hotel brands often lose their editorial quality the moment they move to social — overloaded with promotional text, price callouts, and generic stock imagery that contradicts the premium experience they're selling.",
        "solution": "I developed a content direction built on cinematic restraint: wide compositions, deliberate negative space, and typography scaled to whisper rather than announce. Each post is art-directed to stand independently as an image before it functions as an advertisement.",
        "results": ["Established an editorial social media identity for luxury positioning", "Produced a scalable content template system across multiple hospitality brands", "Elevated visual perception through composition and restraint, not production budget", "Built a content architecture that works equally well for feed, stories, and paid placements"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/social media web-04.jpg"]
      },
      {
        "id": "seasonal-campaigns",
        "name": "Seasonal & Cultural Campaigns",
        "year": "2026",
        "category": "Seasonal Marketing",
        "industry": "Advertising",
        "blurb": "Campaigns built on cultural understanding, not just a calendar date.",
        "overview": "Seasonal campaigns demand more than attractive graphics — they require emotion, cultural fluency, and timing that feels earned rather than opportunistic. This collection features promotional visuals for Ramadan, Eid, national celebrations, and hospitality events. Every design balances typography, photography, and storytelling to create content that feels like it was made for the moment, not repurposed from last year.",
        "services": ["Creative Direction", "Art Direction", "Advertising Design", "Photo Manipulation"],
        "deliverables": ["Instagram Posts", "Stories", "Facebook Campaign Visuals", "Carousel Posts", "Seasonal Campaign Series"],
        "software": ["Photoshop", "Illustrator", "After Effects"],
        "challenge": "Brands that produce seasonal content for cultural occasions typically recycle the same iconography year after year. The result is content that audiences scroll past on autopilot — they've seen the crescent and the lantern a thousand times already.",
        "solution": "Each campaign started with the emotional texture of the occasion — what it feels like, not just what it looks like. From there, design decisions around color temperature, typographic weight, and compositional structure were all made in service of that specific feeling.",
        "results": ["Produced culturally resonant campaign content across Ramadan, Eid, and national occasions", "Developed a seasonal content framework adaptable across brands and formats", "Created visually distinct campaigns with no repeated visual language between them", "Delivered all assets platform-optimized and publication-ready"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/social media web-02.jpg"]
      },
      {
        "id": "personal-brand",
        "name": "Personal Brand Content",
        "year": "2026",
        "category": "Personal Brand",
        "industry": "Brand Marketing",
        "blurb": "A content system that makes a person recognisable before the name is read.",
        "overview": "Personal brand work is harder than it looks. Anyone can make something pretty. The challenge is making content that has a consistent editorial point of view, sounds like a real person, and gives an audience a reason to follow rather than scroll past. This system was built around a signature color, one headline typeface, and spacing rules strict enough that every post feels like it came from the same hand. It looks like a magazine. It performs like one too.",
        "services": ["Content Strategy", "Art Direction", "Social Media Design", "Visual Identity"],
        "deliverables": ["Instagram Posts", "Stories Templates", "Carousel Posts", "Highlight Covers", "Reels Cover Frames", "Feed Grid Layout"],
        "software": ["Photoshop", "Illustrator"],
        "challenge": "Without a clear editorial point of view, personal brand content looks like a collection of individual posts rather than a coherent presence. The audience has no visual hook to remember — nothing that makes a new post immediately recognisable as belonging to this person.",
        "solution": "I reduced the visual system to three non-negotiables: one signature accent color, one headline typeface, and a fixed grid of margins and proportions. From those constraints, every post format generates itself. Coherence becomes structural rather than effortful.",
        "results": ["Established a strong, immediately recognisable personal brand presence", "Built a design system that produces consistent output without constant creative decisions", "Delivered a template library covering all major content formats", "Improved overall feed coherence across a diverse content calendar"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/personal brand.jpg"]
      },
      {
        "id": "events-entertainment",
        "name": "Events & Entertainment Campaigns",
        "year": "2026",
        "category": "Event Marketing",
        "industry": "Entertainment",
        "blurb": "Visuals that make an event feel unmissable before the first ticket is sold.",
        "overview": "Entertainment marketing is about creating desire before the event exists in anyone's experience. This collection features promotional campaigns for themed nights, live performances, DJ events, and luxury hospitality evenings. Each visual uses typography scale, cinematic lighting references, and compositional drama to build the kind of anticipation that converts scrollers into attendees.",
        "services": ["Campaign Design", "Advertising Design", "Photo Manipulation", "Event Poster Design"],
        "deliverables": ["Instagram Posts", "Stories", "Event Posters", "Facebook Ads", "Display Banners", "Square & Landscape Formats"],
        "software": ["Photoshop", "Illustrator", " "],
        "challenge": "Event promotion for nightlife and hospitality brands competes in one of the most visually saturated corners of social media. Most campaigns use the same playbook — neon type, dark backgrounds, artist headshots — and audiences stop seeing them.",
        "solution": "Each campaign was built around the specific atmosphere and emotion of the individual event, not a generic 'nightlife' template. Typography scale, color temperature, and image treatment were calibrated to each occasion, creating distinct visual identities even within a single venue's content calendar.",
        "results": ["Created a series of high-impact promotional campaigns with no shared visual language", "Built event-specific creative frameworks adaptable to recurring formats", "Produced assets covering all social formats and paid placement sizes", "Developed a content approach that treats event promotion as editorial storytelling"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/social media web-05.jpg"]
      },
      {
        "id": "sports-campaigns",
        "name": "Sports Campaigns",
        "year": "2026",
        "category": "Sports Marketing",
        "industry": "Sports",
        "blurb": "Match day content that carries brand identity and stadium energy simultaneously.",
        "overview": "Sports content moves fast, and every design has a matter of seconds to land. This collection combines bold typography, player-driven compositions, and cinematic color grading for football match promotions, tournament campaigns, and hospitality brands activating around sporting events. Each design builds anticipation without borrowing the generic football graphic language that makes most sports content invisible.",
        "services": ["Campaign Design", "Advertising Design", "Photo Manipulation", "Social Media Design"],
        "deliverables": ["Match Day Posts", "Stories", "Tournament Campaign Visuals", "Facebook Ads", "Social Templates"],
        "software": ["Photoshop", "Illustrator"],
        "challenge": "Sports content for restaurants and hospitality venues has a dual audience problem: it has to carry the excitement of the match while also representing the brand producing it. Most designers solve this by abandoning the brand entirely in favour of generic sports graphics.",
        "solution": "I developed a hybrid visual language where each design leads with the sporting moment — player energy, match tension, tournament stakes — while the client's color system and typographic identity anchor every composition. The result reads as promotional and on-brand simultaneously.",
        "results": ["Produced a flexible sports campaign system across multiple venues and match days", "Created visual assets that maintained brand identity within sporting contexts", "Delivered a reusable template structure covering all fixture types", "Established a distinct visual voice in a heavily commoditised content category"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/social media web-03.jpg"]
      },
      {
        "id": "creative-concepts",
        "name": "Creative Concepts",
        "year": "2026",
        "category": "Experimental Design",
        "industry": "Creative Agency",
        "blurb": "Exploratory work with no brief, no guardrails, and occasionally the best results.",
        "overview": "Not every project comes with guardrails. These pieces were made to explore — texture against typography, unexpected color combinations, layouts that break the grid on purpose. This is where design instincts get tested without the pressure of a client approval. Some of it becomes the direction for the next real brief. All of it sharpens the eye for the work that matters.",
        "services": ["Concept Development", "Visual Exploration", "Experimental Design", "Art Direction"],
        "deliverables": ["Concept Visuals", "Experimental Layouts", "Campaign Direction Mockups", "Visual Research Assets"],
        "software": ["Photoshop", "Illustrator"],
        "challenge": "Self-directed creative work without a brief or audience can easily become purposeless visual exercise. The risk is producing something that looks interesting in isolation but has no transferable creative logic.",
        "solution": "Each piece was built around a single, defined visual tension — two opposing ideas held in deliberate conflict. That constraint forces every element to justify itself and produces work that feels resolved even when it operates outside conventional rules.",
        "results": ["Built a personal visual research library that actively informs client work", "Developed compositional and typographic techniques now used across multiple projects", "Established a consistent experimental practice alongside commercial output", "Produced a body of speculative work with its own coherent creative identity"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/creative social.jpg"]
      },
      {
        "id": "sustainable-visual",
        "name": "Sustainable Visual Content",
        "year": "2026",
        "category": "Brand Content",
        "industry": "Brand Marketing",
        "blurb": "Honest design for brands that have earned the right to the aesthetic.",
        "overview": "Greenwashing is obvious. Sustainable brands that actually mean it need content that earns the aesthetic rather than borrowing it. This series works in natural tones — unbleached paper, muted sage, warm cream — with photography-forward compositions and typography that doesn't announce itself. The visual language says 'we've thought about this' without having to say it out loud.",
        "services": ["Art Direction", "Content Design", "Social Media Design"],
        "deliverables": ["Instagram Posts", "Stories", "Carousel Posts", "Campaign Visuals", "Social Templates"],
        "software": ["Photoshop", "Illustrator"],
        "challenge": "The visual language of sustainability has become so widely adopted that it no longer communicates genuine commitment — earth tones and raw textures have become a category convention rather than an honest signal. Brands that actually operate sustainably need content that rises above the aesthetic.",
        "solution": "I stripped the system back to its essentials: natural tones used with real restraint, photography that prioritises authenticity over production value, and typography quiet enough to let the subject matter speak. No performative roughness. No borrowed signifiers. Just honest visual choices.",
        "results": ["Developed an authentic content identity that differentiates within a saturated category", "Created a visual system that communicates values through design decisions, not copy", "Built a template architecture adaptable across product lines and posting schedules", "Established an editorial tone consistent across feed, stories, and carousel formats"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/sutainable.jpg"]
      },
      {
        "id": "audio-podcast",
        "name": "Audio & Podcast Visuals",
        "year": "2026",
        "category": "Podcast Branding",
        "industry": "Entertainment",
        "blurb": "Cover art engineered to stop a scroll at thumbnail size.",
        "overview": "Podcast visuals have one job: make someone choose this show over the one next to it in a grid of fifty. The shows that build audiences are the ones with a genuine visual identity — a color story, type that reads at 200 by 200 pixels, and a personality you recognize before you read the name. This work covers cover art, episode thumbnails, audiogram templates, and promotional assets designed to be reproducible quickly without losing quality.",
        "services": ["Visual Identity", "Art Direction", "Social Media Design"],
        "deliverables": ["Podcast Cover Art", "Episode Thumbnail Templates", "Audiogram Templates", "Promotional Posts", "Stories Assets"],
        "software": ["Photoshop", "Illustrator", " "],
        "challenge": "Podcast cover art is almost always an afterthought — a headshot, a show name, a colour background. The resulting covers are illegible at the scale they're actually experienced: a small square in a crowded directory. Visual differentiation at that size requires a completely different approach to design.",
        "solution": "Every design was built at 200×200 pixels first, then scaled up. Only elements that survived the small-format test made it into the final composition. Bold type hierarchies, high-contrast palettes, and reduced detail ensure each cover remains instantly identifiable regardless of context or screen.",
        "results": ["Created a distinctive podcast visual identity optimised for platform discovery", "Built a scalable template system enabling consistent episode-by-episode output", "Developed audiogram designs that perform across Instagram, Twitter, and YouTube Shorts", "Improved show recognition through systematic visual differentiation from the genre default"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/audio podcast.jpg"]
      },
      {
        "id": "real-estate",
        "name": "Real Estate Content",
        "year": "2026",
        "category": "Real Estate & Architecture",
        "industry": "Real Estate",
        "blurb": "Property content that makes people want to live there before they know the price.",
        "overview": "Real estate social media is a category in desperate need of creative intervention. Stock imagery, identical grid layouts, bold price callouts — the visual language signals 'classified ad,' not 'desirable home.' This series takes the opposite approach: architectural photography treated as editorial content, listing details presented through restraint rather than emphasis, and a design language that makes every post feel like it belongs in a shelter magazine.",
        "services": ["Creative Direction", "Editorial Design", "Social Media Design", "Art Direction"],
        "deliverables": ["Instagram Feed Posts", "Property Listing Carousels", "Stories Templates", "Facebook Campaign Visuals", "Display Ads"],
        "software": ["Photoshop", "Illustrator"],
        "challenge": "The default real estate content vocabulary — white background, property exterior, price in large red type — communicates urgency and transaction rather than aspiration and lifestyle. Brands trying to sell premium properties need content that attracts buyers who are shopping for a feeling.",
        "solution": "I reframed each property as an editorial subject rather than a product listing. Architectural photography was treated with the same compositional care as magazine imagery — wide, atmospheric, and allowed to breathe. Typography was restrained to the minimum needed for utility, letting the space sell itself.",
        "results": ["Built an editorial content system that repositions listings as aspirational experiences", "Created a visual language that differentiates premium properties from generic competition", "Established a reusable design framework adaptable across property types and price points", "Produced content that performs equally well as organic posts and paid placements"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/real estate.jpg"]
      },
      {
        "id": "food-restaurant",
        "name": "Food & Restaurant Content",
        "year": "2026",
        "category": "Food & Hospitality",
        "industry": "Restaurant",
        "blurb": "The design layer that makes food photography do more work.",
        "overview": "Good food content isn't just about the shot. It's about how the image sits in the grid, what typeface carries the dish name, whether the color grade makes the food look hot or cold. This work handles everything around the photograph: the overlays, the type treatments, the campaign layouts that transform a single food image into a piece of content that actually represents the restaurant's character.",
        "services": ["Content Design", "Advertising Design", "Social Media Design", "Art Direction"],
        "deliverables": ["Instagram Posts", "Stories", "Promotional Campaign Visuals", "Carousel Posts", "Facebook Ads", "Seasonal Campaign Assets"],
        "software": ["Photoshop", "Illustrator"],
        "challenge": "Restaurant social media suffers from a disconnect between food quality and content quality. Excellent photography gets buried in layouts that compete with it — busy backgrounds, mismatched type, decorative elements that draw the eye away from the dish itself.",
        "solution": "I built a content system designed to serve the photography rather than frame it. Typography scales in direct proportion to the space the image needs; colour treatments follow the palette of the dish itself; layouts are structured so the food is always the first thing the eye lands on.",
        "results": ["Developed a content design system that strengthens rather than competes with food photography", "Created campaign templates adaptable to daily specials, seasonal menus, and event promotions", "Produced a full suite of social assets covering every platform format and placement type", "Built a reusable creative framework enabling consistent content production without creative overhead"],
        "cover": "img/work/social media-01.jpg",
        "gallery": ["img/work/food.jpg"]
      }
    ],

    "3d-design": [
      {
        "id": "ancient-relic",
        "name": "Ancient Relic Scene",
        "year": "2026",
        "category": "Cinematic 3D",
        "industry": "Entertainment",
        "blurb": "Rendered like it was pulled from a sealed vault and lit for the first time.",
        "overview": "A self-directed cinematic brief: render an object that communicates centuries of history without a single word of context. The trophy-relic is constructed from beaten gold, aged octagonal medallions, and ribbons that catch volumetric light differently at every angle. The real technical work was in the particles — atmospheric dust suspended in the beam of a single directional light, giving the impression of an object that has been sitting in darkness for a very long time and someone just opened the door.",
        "services": ["3D Modeling", "Lighting", "Rendering", "Creative Direction"],
        "deliverables": ["Hero Render", "Atmospheric Close-up", "High-Resolution Portfolio Assets"],
        "software": ["Blender", "Photoshop"],
        "challenge": "Communicating age, weight, and historical significance through a purely synthetic 3D object — without real-world texture reference, without physical material to reference, and without any narrative context beyond the image itself.",
        "solution": "I built material imperfection into every surface: irregular wear patterns in the gold, micro-scratches across the medallions, and asymmetric aging on the ribbons. Volumetric scattering and atmospheric particles completed the scene — the environment tells the object's story so the form doesn't have to.",
        "results": ["Produced a self-directed cinematic render with a strong narrative presence", "Advanced proficiency in volumetric lighting and particle systems within Blender", "Created a high-resolution portfolio asset demonstrating storytelling through 3D", "Developed a material imperfection workflow now applied across commercial renders"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-04.jpg"]
      },
      {
        "id": "interior-visualization",
        "name": "Modern Interior",
        "year": "2026",
        "category": "Architectural Visualization",
        "industry": "Architecture",
        "blurb": "A CGI living room that feels occupied rather than showroom-perfect.",
        "overview": "The defining failure of interior visualization is the showroom effect — that uncanny stillness where every surface is pristine, every cushion is centred, and the room feels like no one has ever been in it. This scene was designed against that tendency. Afternoon light enters from one side and falls unevenly. The wood floor has visible grain variation. The cushions are slightly asymmetric. The wall art is the kind someone actually chose, not the kind that filled the frame at the shop.",
        "services": ["3D Modeling", "Lighting", "Architectural Visualization", "Rendering"],
        "deliverables": ["Hero Interior Render", "Detail Close-ups", "Ambient Lighting Study", "High-Resolution Presentation Assets"],
        "software": ["Blender", "Photoshop"],
        "challenge": "Achieving believable habitability in a fully synthetic scene — making a space feel as though real people have spent time in it, without introducing elements that read as deliberately staged imperfection.",
        "solution": "I approached the scene like a set dresser rather than a product photographer — working from the lived-in state backward. Asymmetry, wear, and material variation were built into the geometry and shading from the start rather than added as post-production detail. Light directionality was calibrated to a specific time of day and compass orientation.",
        "results": ["Produced a photorealistic interior visualization that passes the uncanny valley test", "Developed a natural light simulation approach applicable to future architectural projects", "Built high-resolution assets suitable for client pitch presentations", "Advanced understanding of how material variation and imperfection drive photorealism"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-13.jpg"]
      },
      {
        "id": "jewelry-render",
        "name": "Luxury Jewelry Render",
        "year": "2026",
        "category": "Product Visualization",
        "industry": "Luxury Branding",
        "blurb": "Materials pushed to the point where the render earns the word luxury.",
        "overview": "Jewelry visualization fails the moment a material reads as approximation rather than substance. Gold that looks merely yellow rather than reflective and complex; stones that feel painted-on rather than refracting from within — both destroy the image immediately. This piece treated material accuracy as the primary design challenge. The gold catches light at multiple vectors simultaneously. The stones shift from transparent to opaque depending on angle. The composition is deliberately minimal so the materials are the only subject.",
        "services": ["3D Modeling", "Product Visualization", "Lighting", "Rendering"],
        "deliverables": ["Hero Product Render", "Close-up Detail Renders", "E-Commerce Assets", "Campaign Visuals"],
        "software": ["Blender", "Photoshop"],
        "challenge": "Physically accurate precious metal and gemstone shaders are among the most technically demanding materials in 3D rendering — gold without warm yellow contamination, diamonds with correct internal dispersion, and settings that create physically plausible micro-shadows.",
        "solution": "I developed custom PBR material nodes for each metal zone and gem type, referencing physically accurate IOR data and real gemmological photography. The lighting setup uses three sources at divergent angles to create the complex, shifting reflections that signal genuine material richness.",
        "results": ["Achieved photorealistic precious material rendering at commercial standard", "Built a material library for gold and gemstone variations applicable to future commissions", "Produced campaign-quality assets requiring no post-production retouching", "Demonstrated a luxury product visualization workflow from mesh to final delivery"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-14.jpg"]
      },
      {
        "id": "classical-bust",
        "name": "Classical Bust Study",
        "year": "2026",
        "category": "Lighting Study",
        "industry": "Creative Agency",
        "blurb": "A sculptor's subject. A cinematographer's lighting. One image.",
        "overview": "Classical sculpture visualization exists on a spectrum between archaeological documentation and dramatic reinterpretation. This render chose the dramatic end. A single key light from above-left creates the kind of chiaroscuro that makes stone feel like skin — or at least like something that was once warm. The subsurface scattering in the surface material is calibrated so light penetrates slightly before scattering back, replicating the way real marble diffuses a directional source. The result is a bust that belongs in a director's showreel, not a museum catalogue.",
        "services": ["3D Modeling", "Lighting", "Rendering"],
        "deliverables": ["Cinematic Bust Render", "Lighting Study Documentation", "High-Resolution Portfolio Asset"],
        "software": ["Blender", "Photoshop"],
        "challenge": "Replicating stone's optical behaviour in 3D — its particular way of absorbing and diffusing light just below the surface rather than reflecting it from a single plane — while using a dramatic single-source lighting setup that would expose any material inaccuracy immediately.",
        "solution": "I calibrated subsurface scattering values against reference photographs of real Carrara marble under directional studio lighting, iterating until the shadow-to-light transition replicated the gradual translucency of the real material. The single-source setup was chosen specifically because it offers nowhere to hide material errors.",
        "results": ["Mastered subsurface scattering for stone and skin-like materials", "Produced a cinematic render that functions as both technical demonstration and visual statement", "Developed a single-source lighting discipline applicable to portraiture and product work", "Created a reference-quality study now used to calibrate material work on subsequent projects"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-15.jpg"]
      },
      {
        "id": "floral-perfume",
        "name": "Floral Perfume Concept",
        "year": "2026",
        "category": "Product Visualization",
        "industry": "Cosmetics",
        "blurb": "Glass, botanicals, and backlight — a fragrance render built on beautiful opposites.",
        "overview": "Fragrance visualization is a problem of contradiction: the bottle is hard, geometric, and precise; the scent it contains is soft, organic, and invisible. This render resolves that contradiction by making the invisible tangible — botanicals caught mid-fall around the glass, their presence implying what the bottle holds without opening it. Backlighting makes the glass glow from within while soft fill keeps the petals legible. The image communicates the product's character before any text appears.",
        "services": ["3D Modeling", "Product Visualization", "Lighting", "Rendering"],
        "deliverables": ["Hero Product Render", "Campaign Visual", "Studio Close-up", "E-Commerce Assets", "High-Resolution Marketing Material"],
        "software": ["Blender", "Photoshop"],
        "challenge": "Glass is physically complex to render correctly — it simultaneously refracts, reflects, and transmits light, and a convincing result requires accurately modelling all three behaviours. Compositing botanical elements into the same scene without creating visual clutter added a secondary compositional challenge.",
        "solution": "I used a three-layer lighting system: a strong backlight for the glass glow, a soft lateral fill for the botanical elements, and a narrow specular source for the bottle's defining highlight. Petal placement was choreographed in multiple iterations until the elements framed the bottle without competing for attention.",
        "results": ["Produced a premium fragrance visualization at commercial advertising standard", "Mastered multi-layer glass rendering with accurate refraction and transmission", "Built a botanical simulation and placement workflow applicable to future cosmetics projects", "Delivered campaign-ready assets requiring no additional post-production"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-03.jpg"]
      },
      {
        "id": "luxury-perfume",
        "name": "Luxury Fragrance Series",
        "year": "2026",
        "category": "Product Visualization",
        "industry": "Cosmetics",
        "blurb": "Same bottle. Four lighting setups. A proof that light is the real product.",
        "overview": "This series began as a single question: how many distinct brand stories can a single object tell if the only variable is light? The answer: more than expected. The same fragrance bottle appears across four renders — cold directional blue for an austere mood, warm venetian-blind shadows for something more sensual, near-darkness for menace, diffuse studio white for accessibility. No geometry changes. No retouching. Lighting alone carries the entire emotional range.",
        "services": ["Product Visualization", "Lighting", "Rendering", "Creative Direction"],
        "deliverables": ["Multi-Mood Render Series", "Campaign Visual Set", "E-Commerce Assets", "Seasonal Campaign Material"],
        "software": ["Blender", "Photoshop"],
        "challenge": "Demonstrating emotional and brand-mood range through a single object with no props, no background changes, and no retouching — using only lighting to shift the viewer's relationship to the same product across four completely different registers.",
        "solution": "I treated each render as a separate cinematographic study: defining the emotional target first, then reverse-engineering the lighting setup required to achieve it. Color temperature, directionality, falloff, and intensity were each calibrated independently for each mood rather than adjusted from a shared starting point.",
        "results": ["Proved through practice that lighting is the primary determinant of luxury product perception", "Produced four commercially viable campaign renders from a single asset and lighting study", "Developed a mood-based lighting methodology now systematically applied to product work", "Built a series that functions simultaneously as portfolio piece and working client reference"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-07.jpg"]
      },
      {
        "id": "designer-furniture",
        "name": "Furniture Visualization",
        "year": "2026",
        "category": "Product Visualization",
        "industry": "Product Design",
        "blurb": "Catalog-quality output where fabric behaves like fabric and wood reads like wood.",
        "overview": "Furniture visualization collapses whenever a material fails its own reference category. Upholstery that looks like rubber. Wood grain that tiles visibly. Proportions measured by eye rather than against real dimensions. This project treated material accuracy as a non-negotiable constraint before any creative decision was made. Fabric displacement maps compress under implied weight. Wood shaders were built from real timber photography. Every dimension was matched against physical references before a single light was set.",
        "services": ["3D Modeling", "Product Visualization", "Lighting", "Rendering"],
        "deliverables": ["Hero Product Render", "Detail Close-ups", "E-Commerce Assets", "Catalog Visuals", "High-Resolution Stills"],
        "software": ["Blender", "Photoshop"],
        "challenge": "Upholstery and timber are two of the most scrutinised material categories in furniture visualization — experienced buyers have handled enough sofas and tables to identify a material inaccuracy within seconds. The technical demands of getting both right simultaneously are compounded by the fact that they respond to light in completely opposite ways.",
        "solution": "Fabric was treated with displacement mapping rather than normal-map simulation, creating genuine surface geometry that responds to lighting direction the way real textile does. The wood shader was constructed from multiple layered real-world photographic references, with grain direction mapped per surface face rather than uniformly projected.",
        "results": ["Produced catalog-quality furniture renders that pass material accuracy scrutiny", "Developed a fabric displacement workflow delivering photorealistic upholstery at commercial standard", "Created a reusable material library for timber and textile applicable to future interior projects", "Delivered e-commerce-ready assets eliminating the need for physical photography"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-08.jpg"]
      },
      {
        "id": "packaging-concept",
        "name": "Packaging Concept Study",
        "year": "2026",
        "category": "Product & Packaging",
        "industry": "Product Design",
        "blurb": "A packaging render that bridges graphic design and 3D without a seam.",
        "overview": "This project lives at the exact boundary between two disciplines: a packaging mockup where the flat label design and the three-dimensional form have to function as a unified object. Typography must read correctly after wrapping around a curved surface. Print finishes must be accurately simulated in the shader — matte body against a spot-UV label treatment, for instance — so the client sees a faithful representation of what the physical product will look like. Staging is minimal so the packaging remains the subject.",
        "services": ["3D Modeling", "Packaging Design", "Product Visualization", "Rendering"],
        "deliverables": ["3D Packaging Render", "Multiple Angle Views", "Material Finish Studies", "Presentation Mockups", "High-Resolution Assets"],
        "software": ["Blender", "Illustrator", "Photoshop"],
        "challenge": "Typography and graphic design elements that read correctly in flat 2D almost always distort when projected onto curved packaging geometry. The degree of distortion depends on the surface curvature and viewing angle, and compensating for it requires iterative UV adjustment rather than a single correction.",
        "solution": "I built a UV mapping workflow with iterative label distortion compensation — testing the typographic read at fifteen-degree increments around the full circumference, then correcting the flat artwork to account for each visible angle. Print finish simulation was built into the shader stack rather than handled in post-production, so the mockup accurately represents the real-world material.",
        "results": ["Created presentation-quality 3D packaging mockups eliminating the physical prototype stage", "Developed a label distortion compensation workflow for future cylindrical packaging projects", "Produced multi-angle render sets covering all critical customer viewing positions", "Built a material finish simulation system that accurately represents spot-UV, matte, and gloss treatments"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-09.jpg"]
      },
      {
        "id": "tomford-perfume",
        "name": "Dark Luxury Render",
        "year": "2026",
        "category": "Product Visualization",
        "industry": "Luxury Branding",
        "blurb": "The product barely visible. The image completely deliberate.",
        "overview": "The most compelling fragrance advertising doesn't show you the bottle — it makes you feel the bottle. Shadow is the subject here. A near-black background, a single narrow light source raking across the glass at a steep angle, and enough restraint to let the darkness do its work. The bottle emerges gradually — by degree, by reflection, by the slow accumulation of surface detail that the light chooses to reveal. It's a moody image. That was always the point.",
        "services": ["Product Visualization", "Lighting", "Rendering", "Creative Direction"],
        "deliverables": ["Dark-Field Hero Render", "Campaign Atmospheric Visual", "High-Resolution Marketing Asset"],
        "software": ["Blender", "Photoshop"],
        "challenge": "Creating a product image where the product is largely invisible — where darkness functions as an active design element rather than a failure of lighting — while still communicating enough of the object's form and quality to do commercial work.",
        "solution": "I treated light as a narrative tool rather than an illumination tool. The single source was positioned at a steep raking angle calibrated to reveal exactly the edges and surfaces that define the bottle's silhouette — nothing more. Every decision about what to reveal was also a decision about what to withhold.",
        "results": ["Produced a dark-field fragrance render that functions as genuine luxury advertising", "Developed a single-source raking light technique applicable to premium product work across categories", "Created a commercial asset requiring no post-production correction", "Advanced the use of compositional restraint as a primary creative strategy in product visualization"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-10.jpg"]
      },
      {
        "id": "cosmetic-spray",
        "name": "Cosmetic Spray Packaging",
        "year": "2026",
        "category": "Product Visualization",
        "industry": "Cosmetics",
        "blurb": "A spray render where the specular highlight does exactly what it's supposed to.",
        "overview": "Cylindrical packaging looks deceptively simple until you have to render it. The label must read correctly as it wraps the full circumference. The pump mechanism has at least three distinct material zones — body, ferrule, actuator — each responding to light differently. And the specular highlight that runs vertically down the bottle's surface is the single element that decides whether the result looks like commercial-quality plastic or like something genuinely worth purchasing. This render got it right.",
        "services": ["3D Modeling", "Product Visualization", "Lighting", "Rendering"],
        "deliverables": ["Hero Product Render", "Detail Close-up", "E-Commerce Assets", "Campaign Visual", "Turntable Angle Series"],
        "software": ["Blender", "Photoshop", "Illustrator"],
        "challenge": "The pump mechanism on a spray bottle requires modeling at a level of geometric detail most product renders approximate — each sub-component needs its own material treatment, and the assembly must be dimensionally accurate for the overall render to read as credible.",
        "solution": "I modeled the pump assembly at full physical accuracy, then built separate material shaders for each zone: matte ABS body, satin chrome ferrule, and gloss-coated actuator with distinct roughness values. Studio lighting was calibrated until the specular highlight produced the classic elongated reflection that signals quality on cylindrical plastic.",
        "results": ["Produced a commercial-standard cosmetic spray render accurate to real-world manufacturing details", "Developed a multi-component pump assembly modeling and shading workflow", "Created e-commerce and campaign assets meeting retail platform technical requirements", "Built a multi-material cylinder workflow applicable across spray, pump, and bottle formats"],
        "cover": "img/work/3d-01.jpg",
        "gallery": ["img/work/3d-11.jpg"]
      }
    ],

    "video-editing": [
      {
        "id": "video-edit-reel",
        "name": "Video Editing & Motion",
        "year": "2026",
        "category": "Video Editing",
        "industry": "Advertising",
        "blurb": "Editing that disappears into the content — visible only in what it achieves.",
        "overview": "Good editing is invisible. You only notice cuts when they're wrong — when the pacing drags, when a transition draws attention to the editor rather than the content, when the text animation lingers two seconds past the point it stopped adding anything. This reel covers social content, brand campaigns, and short-form edits across multiple formats and industries. The consistent discipline: every cut is motivated, every motion graphic earns its frame, and the whole thing moves at whatever speed the content actually needs.",
        "services": ["Video Editing", "Motion Design", "Colour Grading", "Creative Direction"],
        "deliverables": ["Vertical Reels", "Landscape Brand Films", "Square Format Social Edits", "Animated Titles", "Motion Graphics", "Social Ads"],
        "software": ["Premiere Pro", "After Effects"],
        "challenge": "Short-form social content has a shrinking attention window — establishing context, communicating a message, and motivating action within a two-second hook. Most edits sacrifice communicative clarity for visual spectacle, producing content that looks impressive in isolation but fails its commercial objective.",
        "solution": "I imposed a strict editorial logic on every sequence: the hook must work before the first cut, every transition must be motivated by content rather than style, and every motion graphic must add information rather than decoration. Pacing decisions were made by what the piece needed to communicate, not what looked dynamic in a showreel.",
        "results": ["Produced a diverse editing reel covering social, brand, and short-form categories", "Established a restrained motion design vocabulary now applied consistently across all video work", "Created platform-specific exports covering all aspect ratios and technical specifications", "Demonstrated an editorial discipline that prioritises communication over spectacle"],
        "cover": "img/work/cover videoedit.jpg",
        "gallery": [
          "vid/editvideo/Comp 1.mp4",
          "vid/editvideo/Comp 2.mp4",
          "vid/editvideo/Comp 3.mp4",
          "vid/editvideo/Comp 4.mp4",
          "vid/editvideo/Comp 5.mp4",
          "vid/editvideo/Comp 6.mp4",
          "vid/editvideo/Comp 7.mp4"
        ]
      },
      {
        "id": "3d-vfx",
        "name": "3D Animation & VFX",
        "year": "2026",
        "category": "3D Motion & VFX",
        "industry": "Entertainment",
        "blurb": "Eight sequences. Product reveals, cinematic scenes, and objects that don't exist placed into footage of the world that does.",
        "overview": "This collection represents the full scope of 3D animation and VFX compositing work: a golden trophy rising through volumetric dust, a three-panel product sequence with jewelry and fragrance moving in synchronized choreography, a cinematic interior walkthrough under warm raking light, an abstract sphere composition in deep red on a reflective grid, a luxury perfume reveal, and VFX compositing that integrates rendered geometry into real-world footage. Every sequence was modeled, animated, and lit in Blender before being composited and graded for a consistent cinematic look across the set.",
        "services": ["3D Animation", "VFX Compositing", "Motion Design", "Colour Grading", "Rendering"],
        "deliverables": ["3D Animated Sequences", "VFX Composite Shots", "Product Reveal Animations", "Cinematic Stills", "Motion Graphics"],
        "software": ["Blender", "After Effects", "Premiere Pro"],
        "challenge": "Integrating rendered 3D objects into real-world footage requires the virtual camera, the lighting environment, and the motion dynamics of the CG elements to match the physical properties of the filmed scene exactly. Any discrepancy in perspective, shadow colour, or motion blur is immediately visible to the viewer.",
        "solution": "Each VFX composite began with a detailed lighting analysis of the real-world footage — measuring shadow direction, color temperature, and ambient fill levels before touching the 3D environment. Camera tracking data from the original footage drove the virtual camera, and motion blur settings were matched frame-by-frame to the practical camera's specifications.",
        "results": ["Produced a complete 3D animation and VFX showreel across eight distinct visual categories", "Established a production-accurate VFX compositing workflow from tracking to final grade", "Demonstrated the full pipeline from 3D asset creation through motion, compositing, and delivery", "Built motion assets across product, environmental, abstract, and live-action integration genres"],
        "cover": "img/work/vfx cover.jpg",
        "gallery": [
          "vid/Comp 1.mp4",
          "vid/Comp 2.mp4",
          "vid/Comp 3.mp4",
          "vid/Comp 4.mp4",
          "vid/Comp 5.mp4",
          "vid/Comp 6.mp4",
          "vid/Comp 7.mp4",
          "vid/Comp 8.mp4"
        ]
      }
    ],

    "menu-design": [
      {
        "id": "restaurant-menu",
        "name": "Restaurant Menu",
        "year": "2025",
        "category": "Print & Menu Design",
        "industry": "Restaurant",
        "blurb": "A menu that feels like the dining room — same materials, same intent, same care.",
        "overview": "A restaurant menu is the only piece of print design that every single customer touches. It's held for minutes, returned to multiple times, and read in low light by people who are already forming an opinion about the experience. This design approached those constraints directly — typographic hierarchy calibrated for readability at table lighting levels, section structure designed to guide rather than overwhelm, and material choices that extend the interior identity into the guest's hands.",
        "services": ["Print Design", "Editorial Layout", "Typography", "Brand Applications"],
        "deliverables": ["Full Menu Layout", "Cover Design", "Section Dividers", "Print-Ready Files", "Digital PDF Version"],
        "software": [" ", "Illustrator", "Photoshop"],
        "challenge": "Restaurant menus frequently undermine the quality of the dining experience before the food arrives — mismatched typography, unclear information hierarchy, and layouts that make navigating a menu feel like searching a poorly formatted document.",
        "solution": "I designed the hierarchy from the guest's reading behaviour outward: category headers calibrated to scan quickly, dish names and descriptions set at optimal table-reading point sizes, and section transitions that feel like natural pauses rather than abrupt breaks. Material and finish choices were specified to complement the interior design rather than sit as a separate object.",
        "results": ["Delivered a print-ready menu system that extends the restaurant's brand identity into the dining experience", "Built a layout architecture that scales easily for seasonal menu revisions", "Established typographic standards that remain legible in low ambient lighting conditions", "Produced a design system that unifies menu, signage, and stationery across the restaurant"],
        "cover": "img/work/menu-restaurant-cover.jpg",
        "gallery": ["img/work/menu-restaurant-cover.jpg"]
      },
      {
        "id": "cafe-menu",
        "name": "Café Menu",
        "year": "2025",
        "category": "Print & Menu Design",
        "industry": "Food & Beverage",
        "blurb": "Designed for the counter — clear at a glance, warm at a second look.",
        "overview": "A café menu lives in a specific, demanding context: read standing up, at speed, often under overhead lighting, by someone who has already been waiting. The design has to be scannable in seconds and considered enough to communicate quality. This menu achieves both — a warm, restrained palette and unhurried typography that communicates craft, set within a layout hierarchy strict enough to guide any customer to what they want before the person ahead of them has finished ordering.",
        "services": ["Print Design", "Editorial Layout", "Typography"],
        "deliverables": ["Counter Menu", "Printed Board Menu Artwork", "Takeaway Card", "Print-Ready Files", "Digital PDF"],
        "software": [" ", "Illustrator", "Photoshop"],
        "challenge": "Café menus are frequently over-designed for the context in which they're actually used. Decorative layouts, fine-weight type, and insufficient contrast work against legibility at counter distance and under the warm, uneven lighting of most café interiors.",
        "solution": "I designed the layout from the worst-case reading conditions inward — low contrast, counter distance, and time pressure. Every typographic decision was tested against those conditions before any aesthetic choices were made. Warmth and character came through palette and spacing rather than decorative elements.",
        "results": ["Designed a counter menu that performs under real café operating conditions", "Established a typographic hierarchy legible at standing distance in variable lighting", "Built a layout system adaptable for seasonal drink additions without restructuring", "Delivered a menu that communicates the café's quality through restraint and considered detail"],
        "cover": "img/work/menu-cafe-cover.jpg",
        "gallery": ["img/work/menu-cafe-cover.jpg"]
      }
    ],

    "ui-website": [
      {
        "id": "landing-page",
        "name": "Landing Page Design",
        "year": "2026",
        "category": "UI & Web Design",
        "industry": "Corporate",
        "blurb": "One goal. Every section in service of it.",
        "overview": "A landing page with one job: convert. Every section was designed in explicit service of a single user action — the hero establishes the value proposition in under five seconds, the supporting sections address objections in the order visitors typically raise them, and the CTA appears at every natural pause in the scroll without ever feeling pushy. Clean enough to feel premium. Direct enough to actually work.",
        "services": ["UI Design", "Web Design", "UX Strategy"],
        "deliverables": ["Wireframes", "UI Design", "Figma Prototype", "Responsive Layout", "HTML & CSS Files", "Developer Handoff Documentation"],
        "software": ["Figma", "VS Code", "Photoshop"],
        "challenge": "Landing pages fail at the moment they try to accomplish too much — multiple CTAs pulling in different directions, competing value propositions, visual complexity that erodes confidence rather than building it. Achieving maximum conversion focus while maintaining enough visual quality to signal credibility is a precise design problem.",
        "solution": "I structured the entire page around a single decision path, then worked backwards from the conversion point. Every section was audited against one question: does this help or hinder the primary action? Sections that didn't build toward the conversion were removed; sections that remained were ordered by the typical sequence of visitor objections.",
        "results": ["Designed a focused conversion page eliminating visual and structural noise", "Built a fully responsive layout functioning across all viewport sizes", "Produced clean HTML and CSS output ready for direct deployment", "Established a page architecture and design system applicable to future campaign landing pages"],
        "cover": "img/work/ui-landing-cover.jpg",
        "gallery": ["img/work/ui-landing-cover.jpg"]
      },
      {
        "id": "website-design",
        "name": "Website Design",
        "year": "2026",
        "category": "UI & Web Design",
        "industry": "Corporate",
        "blurb": "A website where the design system does the work of consistency.",
        "overview": "A multi-page website only stays coherent if the design system is built before the pages. This project started with a complete component and style inventory — typography scale, spacing system, color roles, interactive states — before a single page layout was touched. The result is a site that holds its visual identity regardless of who adds content or which page the visitor lands on first, built on WordPress with enough structural discipline that it won't drift over time.",
        "services": ["UI Design", "Web Design", "Design System", "WordPress Development"],
        "deliverables": ["Wireframes", "UI Components Library", "Responsive Design", "Interactive Prototype", "WordPress Build", "Design System Documentation", "Developer Handoff"],
        "software": ["Figma", "WordPress", "VS Code", "Photoshop"],
        "challenge": "Multi-page websites degrade over time because the design system is usually implicit rather than codified — decisions made for the homepage get approximated or ignored on pages added later, and the site gradually develops visual inconsistency that no individual update seems to cause.",
        "solution": "I inverted the typical build sequence: design system first, pages second. Every spacing value, type style, color role, and component variant was defined and documented before any page layouts were created. The WordPress build implements these as structured templates rather than freeform page builders, enforcing consistency at the content entry level.",
        "results": ["Built a multi-page website with a codified design system preventing long-term visual drift", "Created a component library enabling consistent content expansion without design involvement", "Delivered a fully responsive build covering mobile, tablet, and desktop viewport ranges", "Established a WordPress structure that separates design intent from content management"],
        "cover": "img/work/ui-website-cover.jpg",
        "gallery": ["img/work/ui-website-cover.jpg"]
      }
    ]
  }
};
